// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Global
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by XmlSchemaClassGenerator version 2.0.349.0.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable disable
namespace Hestia.Model.Cobertura
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("coverage", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("coverage", Namespace = "")]
    public partial class Coverage
    {
        [System.Xml.Serialization.XmlElementAttribute("sources")]
        public Sources Sources { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Package> _packages;

        [System.Xml.Serialization.XmlArrayAttribute("packages")]
        [System.Xml.Serialization.XmlArrayItemAttribute("package")]
        public System.Collections.ObjectModel.Collection<Package> Packages
        {
            get
            {
                return this._packages;
            }
            private set
            {
                this._packages = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Coverage" /> class.</para>
        /// </summary>
        public Coverage()
        {
            this._packages = new System.Collections.ObjectModel.Collection<Package>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("branch-rate")]
        public decimal BranchRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("branches-covered")]
        public string BranchesCovered { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("branches-valid")]
        public string BranchesValid { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("complexity")]
        public double Complexity { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("line-rate")]
        public decimal LineRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("lines-covered")]
        public string LinesCovered { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("lines-valid")]
        public string LinesValid { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("timestamp")]
        public string Timestamp { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("version")]
        public string Version { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("sources", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("sources", Namespace = "")]
    public partial class Sources
    {
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("packages", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("packages", Namespace = "")]
    public partial class Packages
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Package> _package;

        [System.Xml.Serialization.XmlElementAttribute("package")]
        public System.Collections.ObjectModel.Collection<Package> Package
        {
            get
            {
                return this._package;
            }
            private set
            {
                this._package = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Packages" /> class.</para>
        /// </summary>
        public Packages()
        {
            this._package = new System.Collections.ObjectModel.Collection<Package>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("package", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("package", Namespace = "")]
    public partial class Package
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Class> _classes;

        [System.Xml.Serialization.XmlArrayAttribute("classes")]
        [System.Xml.Serialization.XmlArrayItemAttribute("class")]
        public System.Collections.ObjectModel.Collection<Class> Classes
        {
            get
            {
                return this._classes;
            }
            private set
            {
                this._classes = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Package" /> class.</para>
        /// </summary>
        public Package()
        {
            this._classes = new System.Collections.ObjectModel.Collection<Class>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("branch-rate")]
        public decimal BranchRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("complexity")]
        public double Complexity { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("line-rate")]
        public decimal LineRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("classes", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("classes", Namespace = "")]
    public partial class Classes
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Class> _class;

        [System.Xml.Serialization.XmlElementAttribute("class")]
        public System.Collections.ObjectModel.Collection<Class> Class
        {
            get
            {
                return this._class;
            }
            private set
            {
                this._class = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Classes" /> class.</para>
        /// </summary>
        public Classes()
        {
            this._class = new System.Collections.ObjectModel.Collection<Class>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("class", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("class", Namespace = "")]
    public partial class Class
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Method> _methods;

        [System.Xml.Serialization.XmlArrayAttribute("methods")]
        [System.Xml.Serialization.XmlArrayItemAttribute("method")]
        public System.Collections.ObjectModel.Collection<Method> Methods
        {
            get
            {
                return this._methods;
            }
            private set
            {
                this._methods = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Class" /> class.</para>
        /// </summary>
        public Class()
        {
            this._methods = new System.Collections.ObjectModel.Collection<Method>();
            this._lines = new System.Collections.ObjectModel.Collection<Line>();
        }

        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Line> _lines;

        [System.Xml.Serialization.XmlArrayAttribute("lines")]
        [System.Xml.Serialization.XmlArrayItemAttribute("line")]
        public System.Collections.ObjectModel.Collection<Line> Lines
        {
            get
            {
                return this._lines;
            }
            private set
            {
                this._lines = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute("branch-rate")]
        public decimal BranchRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("complexity")]
        public double Complexity { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("filename")]
        public string Filename { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("line-rate")]
        public decimal LineRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("methods", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("methods", Namespace = "")]
    public partial class Methods
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Method> _method;

        [System.Xml.Serialization.XmlElementAttribute("method")]
        public System.Collections.ObjectModel.Collection<Method> Method
        {
            get
            {
                return this._method;
            }
            private set
            {
                this._method = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Methods" /> class.</para>
        /// </summary>
        public Methods()
        {
            this._method = new System.Collections.ObjectModel.Collection<Method>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("method", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("method", Namespace = "")]
    public partial class Method
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Line> _lines;

        [System.Xml.Serialization.XmlArrayAttribute("lines")]
        [System.Xml.Serialization.XmlArrayItemAttribute("line")]
        public System.Collections.ObjectModel.Collection<Line> Lines
        {
            get
            {
                return this._lines;
            }
            private set
            {
                this._lines = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Method" /> class.</para>
        /// </summary>
        public Method()
        {
            this._lines = new System.Collections.ObjectModel.Collection<Line>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("branch-rate")]
        public decimal BranchRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("complexity")]
        public double Complexity { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("line-rate")]
        public decimal LineRate { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("signature")]
        public string Signature { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("lines", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("lines", Namespace = "")]
    public partial class Lines
    {
        [System.Xml.Serialization.XmlIgnoreAttribute]
        private System.Collections.ObjectModel.Collection<Line> _line;

        [System.Xml.Serialization.XmlElementAttribute("line")]
        public System.Collections.ObjectModel.Collection<Line> Line
        {
            get
            {
                return this._line;
            }
            private set
            {
                this._line = value;
            }
        }

        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Lines" /> class.</para>
        /// </summary>
        public Lines()
        {
            this._line = new System.Collections.ObjectModel.Collection<Line>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.349.0")]
    [System.SerializableAttribute]
    [System.Xml.Serialization.XmlTypeAttribute("line", Namespace = "", AnonymousType = true)]
    [System.Diagnostics.DebuggerStepThroughAttribute]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("line", Namespace = "")]
    public partial class Line
    {
        [System.Xml.Serialization.XmlAttributeAttribute("branch")]
        public bool Branch { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("condition-coverage")]
        public string ConditionCoverage { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("hits")]
        public int Hits { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("number")]
        public int Number { get; set; }
    }
}
#nullable enable
