// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Global
//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by XmlSchemaClassGenerator version 2.0.349.0.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Xml.Serialization;

#nullable disable
namespace Hestia.Model.Cobertura
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("coverage", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("coverage", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Coverage
    {
        [XmlIgnore] private Collection<Package> _packages;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Coverage" /> class.</para>
        /// </summary>
        public Coverage() => _packages = new Collection<Package>();

        [XmlElement("sources")] public Sources Sources { get; set; }

        [XmlArray("packages")]
        [XmlArrayItem("package")]
        public Collection<Package> Packages
        {
            get => _packages;
            private set => _packages = value;
        }

        [XmlAttribute("branch-rate")] public decimal BranchRate { get; set; }

        [XmlAttribute("branches-covered")] public string BranchesCovered { get; set; }

        [XmlAttribute("branches-valid")] public string BranchesValid { get; set; }

        [XmlAttribute("complexity")] public double Complexity { get; set; }

        [XmlAttribute("line-rate")] public decimal LineRate { get; set; }

        [XmlAttribute("lines-covered")] public string LinesCovered { get; set; }

        [XmlAttribute("lines-valid")] public string LinesValid { get; set; }

        [XmlAttribute("timestamp")] public string Timestamp { get; set; }

        [XmlAttribute("version")] public string Version { get; set; }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("sources", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("sources", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Sources
    {
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("packages", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("packages", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Packages
    {
        [XmlIgnore] private Collection<Package> _package;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Packages" /> class.</para>
        /// </summary>
        public Packages() => _package = new Collection<Package>();

        [XmlElement("package")]
        public Collection<Package> Package
        {
            get => _package;
            private set => _package = value;
        }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("package", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("package", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Package
    {
        [XmlIgnore] private Collection<Class> _classes;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Package" /> class.</para>
        /// </summary>
        public Package() => _classes = new Collection<Class>();

        [XmlArray("classes")]
        [XmlArrayItem("class")]
        public Collection<Class> Classes
        {
            get => _classes;
            private set => _classes = value;
        }

        [XmlAttribute("branch-rate")] public decimal BranchRate { get; set; }

        [XmlAttribute("complexity")] public double Complexity { get; set; }

        [XmlAttribute("line-rate")] public decimal LineRate { get; set; }

        [XmlAttribute("name")] public string Name { get; set; }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("classes", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("classes", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Classes
    {
        [XmlIgnore] private Collection<Class> _class;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Classes" /> class.</para>
        /// </summary>
        public Classes() => _class = new Collection<Class>();

        [XmlElement("class")]
        public Collection<Class> Class
        {
            get => _class;
            private set => _class = value;
        }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("class", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("class", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Class
    {
        [XmlIgnore] private Collection<Line> _lines;

        [XmlIgnore] private Collection<Method> _methods;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Class" /> class.</para>
        /// </summary>
        public Class()
        {
            _methods = new Collection<Method>();
            _lines = new Collection<Line>();
        }

        [XmlArray("methods")]
        [XmlArrayItem("method")]
        public Collection<Method> Methods
        {
            get => _methods;
            private set => _methods = value;
        }

        [XmlArray("lines")]
        [XmlArrayItem("line")]
        public Collection<Line> Lines
        {
            get => _lines;
            private set => _lines = value;
        }

        [XmlAttribute("branch-rate")] public decimal BranchRate { get; set; }

        [XmlAttribute("complexity")] public double Complexity { get; set; }

        [XmlAttribute("filename")] public string Filename { get; set; }

        [XmlAttribute("line-rate")] public decimal LineRate { get; set; }

        [XmlAttribute("name")] public string Name { get; set; }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("methods", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("methods", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Methods
    {
        [XmlIgnore] private Collection<Method> _method;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Methods" /> class.</para>
        /// </summary>
        public Methods() => _method = new Collection<Method>();

        [XmlElement("method")]
        public Collection<Method> Method
        {
            get => _method;
            private set => _method = value;
        }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("method", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("method", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Method
    {
        [XmlIgnore] private Collection<Line> _lines;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Method" /> class.</para>
        /// </summary>
        public Method() => _lines = new Collection<Line>();

        [XmlArray("lines")]
        [XmlArrayItem("line")]
        public Collection<Line> Lines
        {
            get => _lines;
            private set => _lines = value;
        }

        [XmlAttribute("branch-rate")] public decimal BranchRate { get; set; }

        [XmlAttribute("complexity")] public double Complexity { get; set; }

        [XmlAttribute("line-rate")] public decimal LineRate { get; set; }

        [XmlAttribute("name")] public string Name { get; set; }

        [XmlAttribute("signature")] public string Signature { get; set; }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("lines", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("lines", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Lines
    {
        [XmlIgnore] private Collection<Line> _line;

        /// <summary>
        ///     <para xml:lang="en">Initializes a new instance of the <see cref="Lines" /> class.</para>
        /// </summary>
        public Lines() => _line = new Collection<Line>();

        [XmlElement("line")]
        public Collection<Line> Line
        {
            get => _line;
            private set => _line = value;
        }
    }

    [GeneratedCode("XmlSchemaClassGenerator", "2.0.349.0")]
    [Serializable]
    [XmlType("line", Namespace = "", AnonymousType = true)]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlRoot("line", Namespace = "")]
    [ExcludeFromCodeCoverage]
    public partial class Line
    {
        [XmlAttribute("branch")] public bool Branch { get; set; }

        [XmlAttribute("condition-coverage")] public string ConditionCoverage { get; set; }

        [XmlAttribute("hits")] public int Hits { get; set; }

        [XmlAttribute("number")] public int Number { get; set; }
    }
}
#nullable enable
