name: Sonar scan

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: Setup SonarScanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/root/.dotnet/tools"
      - name: Install dependencies
        run: dotnet restore src/Hestia.sln
      - name: Run Sonar scanner and upload results to SonarCloud
        env:
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_LOGIN }}
          SONAR_ORG: ${{ secrets.SONAR_ORG }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"marczinusd_hestia" /o:"marczinusd" /d:sonar.login="$SONAR_LOGIN" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.coverageReportPaths="coveragereport\SonarQube.xml"
          dotnet build --no-restore src/Hestia.sln
          dotnet test --no-restore src/Hestia.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" /p:CoverletOutput="coverage.json"
          reportgenerator "-reports:**/coverage.json" "-targetdir:coveragereport" "-reporttypes:Html;HtmlSummary;Cobertura;lcov;XML;JsonSummary;SonarQube"
          dotnet sonarscanner end /d:sonar.login="$SONAR_LOGIN"
